### ISSUE TITLE
*Introduction to Linear Algebra 5th edition* link gives 404

### ISSUE THREAD

**Issue by berserker1** [zslucky/awesome-AI-books#1]

**Comment by zslucky** [comment]
@berserker1 I will check it later

**Comment by zslucky** [comment]
Due to gitlab account blocked, I will find another warehouse for storing books...

**Comment by berserker1** [comment]
Sure, thanks

**Comment by zslucky** [comment]
@berserker1 Issue solved, I moved all books to Yandex.disk.

**Comment by pawandayma** [comment]
Yandex link blocked unable to download
